movies/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "movies"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("search/", views.search, name="search"),
    path("movie_info/", views.movie_info, name="movie_info"),
    path("movie_create/", views.movie_create, name="movie_create"),
    path("genre_search/<str:genre>", views.genre_search, name="genre_search"),
    path("movie_detail/<int:pk>", views.movie_detail, name="movie_detail"),
    path("movie_update/<int:pk>", views.movie_update, name="movie_update"),
]

toy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movies.urls")),
    path("users/", include("users.urls")),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from users import views  # views 모든 함수를 가져온다.
from django.contrib.auth import views as auth_views


app_name = "users"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),  # 코드 추가하기
    path("signup/", views.signup, name="signup"),
]

movies/models.py
from django.db import models

# Create your models here.
RATE_CHOICES = (
    (1, "★"),
    (2, "★★"),
    (3, "★★★"),
    (4, "★★★★"),
    (5, "★★★★★"),
)

class Review(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    grade = models.IntegerField(choices=RATE_CHOICES)

    # 글씨 갯수 그건 테이블 갯수의 문제지
    # 장르의 이름의 길이는 상관이 없음


genre_table = (
    ("액션", "액션"),
    ("스릴러", "스릴러"),
    ("코미디", "코미디"),
    ("로맨스", "로맨스"),
    ("SF", "SF"),
    ("드라마", "드라마"),
    ("애니메이션", "애니메이션"),
)

class Movie(models.Model):
    movie_title = models.CharField(max_length=30)
    summary = models.TextField()
    genre = models.CharField(max_length=80,choices=genre_table)
    start_at = models.DateField()

users/models.py
from django.db import models

# Create your models here.
class user(models.Model):
    username = models.CharField(max_length=10)
    password = models.CharField(max_length=15)
    join_at = models.DateTimeField(auto_now_add=True, verbose_name="가입시간")

    class Meta:
        db_table = "test_user"

movies/forms.py
from dataclasses import field
from pyexpat import model
from .models import Review, Movie
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"

users/forms.py
import email
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    class Meta:
        email = forms.EmailField(label="이메일")

        model = User
        fields = ("username", "password1", "password2", "email")

movies/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from .forms import MovieForm, ReviewForm
from .models import Movie, Review

# Create your views here.


def index(request):
    reviews = Review.objects.all()

    context = {"reviews": reviews}

    return render(request, "movies/index.html", context)


def create(request):
    if request.method == "POST":
        form_R = ReviewForm(request.POST)
        if form_R.is_valid():
            form_R.save()
            return redirect("movies:index")
    else:
        form_R = ReviewForm()
    context = {"form_R": form_R}

    return render(request, "movies/create.html", context)


def delete(reuqest, pk):
    Movie.objects.get(pk=pk).delete()

    return redirect("movies:movie_info")


def search(request):
    search = request.GET.get("search", "")

    if request.GET.get("keyword") == "1":
        reviews = Review.objects.filter(title__icontains=search)

    elif request.GET.get("keyword") == "2":
        reviews = Review.objects.filter(content__icontains=search)
    else:
        #  request.GET.get("keyword") == 3:
        reviews = Review.objects.filter(movie_name__icontains=search)

    context = {"reviews": reviews}

    return render(request, "movies/index.html", context)


def movie_info(request):
    movies = Movie.objects.all()
    context = {"movies": movies}
    return render(request, "movies/movie_info.html", context)


def movie_create(request):
    if request.method == "POST":
        form_M = MovieForm(request.POST)
        if form_M.is_valid():
            form_M.save()
            return redirect("movies:movie_info")
    else:
        form_M = MovieForm()
    context = {"form_M": form_M}

    return render(request, "movies/movie_create.html", context)


def genre_search(request, genre):
    genre = genre
    movies = Movie.objects.filter(genre=genre)
    context = {"movies": movies}
    return render(request, "movies/movie_info.html", context)


def movie_detail(request, pk):
    k = Movie.objects.get(pk=pk)
    j = k.movie_title
    context = {
        "movie": k,
    }
    return render(request, "movies/movie_detail.html", context)


def movie_update(request, pk):
    k = Movie.objects.get(pk=pk)
    if request.method == "POST":
        form_R = MovieForm(request.POST, instance=k)
        if form_R.is_valid():
            form_R.save()
            return redirect("/", k.pk)
    else:
        form_R = MovieForm(instance=k)
    context = {
        "form_R": form_R,
        "j": k,
    }

    return render(request, "movies/movie_update.html", context)

users/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from users.forms import UserForm


# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("users:login")

    else:
        form = UserForm()

    return render(request, "users/signup.html", {"form": form})

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    리뷰쓰기
  </h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_form form_R %}
    <input type="submit" class="btn btn-outline-success" value="생성">
  </form>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    인덱스 페이지 도착</h1>

  <a type="button" class="btn btn-light" href="{% url 'movies:create' %}">
    리뷰쓰기</a>

  {% if reviews%}
    {% for review in reviews %}
      <p>리뷰 제목 :
        {{review.title}}</p>

      {%endfor%}
    {%endif %}

    <!-- {% if review %} {% for review in review %} <p>리뷰 제목 : {{review.title}}</p> {%endfor%} {% endif %} -->
  {% endblock %}

movies/templates/movies/movie_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    영화 정보 추가 !
  </h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_form form_M %}
    <input type="submit" class="btn btn-outline-success" value="생성">
  </form>
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% block content %}
  <h3>
    제목 :
    {{movie.movie_title}}</h3>
  <p>
    장르 :
    {{movie.genre}}</p>
  <h5>
    줄거리 요약 :
    {{movie.summary}}</h5>
  <p>
    개봉 날짜 :
    {{movie.start_at}}</p>
  <a href="{% url 'movies:delete' movie.pk %}" type="button" class="btn btn-outline-success">삭제</a>
  <a href="{% url 'movies:movie_update' movie.pk%}" type="button" class="btn btn-outline-success">수정</a>
{% endblock %}

movies/templates/movies/movie_info.html
{% extends 'base.html' %}

{% block content %}
  <div class="md-3">
    <h1>영화 정보</h1>
  </div>
  <a href="{% url 'movies:movie_create' %}" type="button" class="btn btn-light">
    리뷰쓰기</a>

  {% for movie in movies %}
    <a href="{% url 'movies:movie_detail' movie.pk %}">
      <p>{{ movie.movie_title }}</p>
    </a>
  {% endfor %}
{%endblock %}

movies/templates/movies/movie_update.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    영화 업데이트!
  </h1>
  <form action="{% url 'movies:movie_update' j.pk %}" method="POST">
    {% csrf_token %}
    {% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_form form_R %}
    <input type="submit" class="btn btn-outline-success" value="업데이트">
  </form>
{% endblock %}

users/templates/users/404_errors.html
{%if form.errors %}
  <div class="alert alert-danger">

    <!-- 필드 오류(입력값이 누락되었거나 형식에 맞지 않음) 오류 구문 표시 -->
    {% for field in form %}
      {% for error in field.errors %}

        <div>
          <strong>{{ field.label }}</strong>
          {{ error }}
        </div>

      {% endfor %}
    {% endfor %}

    {% for error in from.non_field_errors %}
      <!-- 넌필드 오류(입력값과 관계없이 발생한 오류) -->
      <div>
        <strong>{{ error }}</strong>
      </div>
    {% endfor %}
  </div>
{% endif %}

<!-- 오류의 두가지 필드 오류(입력값이 누락되었거나 형식에 맞지 않음) 넌필드 오류(입력값과 관계없이 발생한 오류) -->

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    로그인페이지
  </h1>
  <form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    {% include 'users/404_errors.html' %}
    <div class="mb-3">
      <label for="id">사용자 아이디</label>
      <input type="text" class="form-control" name="username" id="username">
    </div>
    <div class="mb-3">
      <label for="password">비밀번호</label>
      <input type="password" class="form-control" name="password" id="password">
    </div>
    <div class="mb-3">
      <button type="submit" class="btn btn-outline-success">로그인</button>
      <a type="button" class="btn btn-success" href="{% url 'users:signup' %}">회원가입</a>
    </div>

  </form>

  <!-- 입력 항목 username과 password는 모두 django.contrib.auth 앱에서 요구하는 필수 항목이다. -->
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    회원가입
  </h1>
  <div class="container my-3">
    <form action="{% url 'users:signup' %}" method="POST">
      {% csrf_token %}
      {% include 'users/404_errors.html' %}

      <div class="mb-3">
        <label for="id">사용자 아이디</label>
        <input type="text" class="form-control" name="username" id="username">

      </div>
      <div class="mb-3">
        <label for="password1">비밀번호</label>
        <input type="text" class="form-control" name="password1" id="password1">
      </div>
      <div class="mb-3">
        <label for="password2">비밀번호 확인</label>
        <input type="text" class="form-control" name="password2" id="password2">
      </div>
      <div class="mb-3">
        <label for="email">이메일</label>
        <input type="text" class="form-control" name="email" id="email">
      </div>

      <div class="mb-3">
        <button type="submit" class="btn btn-success">회원가입</button>
      </button>
    </div>
  </div>
  <!-- <div> <label for="id">사용자 아이디</label> <input type="text" name="username" id="username"> </div> <div> <label for="password">비밀번호</label> <input type="text" name="password" id="password"> </div> <button type="submit">회원가입</button> </form> -->
  <!-- 입력 항목 username과 password는 모두 django.contrib.auth 앱에서 요구하는 필수 항목이다. -->
{% endblock %}